### ISSUE TITLE
Doesn't work with postcss-import

### ISSUE THREAD

**Issue by TrySound** [postcss/postcss-use#17]
``` js
postcss([
    postcssImport,
    use({
        modules: ['postcss-inline-svg']
    })
])
```

Input

``` css
// index.css
@import 'module.css';

.a {
    background: #fff svg-load('logo.svg', fill=red) 50% 50%;
    background-size: contain;
}
```

``` css
// module.css
@use postcss-inline-svg;

.c {
    background: svg-load('logo.svg', fill=blue) 50% 50%;
    background-size: contain;
}

```

output

``` css
.c {
    background: url("data:image/svg+xml;charset=utf-8,...") 50% 50%;
    background-size: contain;
}

.a {
    background: #fff url("data:image/svg+xml;charset=utf-8,...") 50% 50%;
    background-size: contain;
}
```
