### ISSUE TITLE
How to send nested key/value options to plugins

### ISSUE THREAD

**Issue by argyleink** [postcss/postcss-use#41]
I'm on codepen trying to customize the features of my `preset-env` plugin use. I can send `stage` fine, but I'm not sure how to send the `features` object key and value. 

```css
@use postcss-preset-env {
  stage: 0,
  features: {
    "logical-properties-and-values": false
  }
} 
```

I have the feature disabled in a local postcss setup, so i know the key/value is good. But on Codepen, it seems to be thrown away, or I can't figure out how to get the syntax right.

Help?
