### ISSUE TITLE
"... is not a valid postcss plugin"

### ISSUE THREAD

**Issue by cjcheshire** [postcss/postcss-use#7]
I'm doing a postcss spike.  Hopefully pretty basic stuff...

The css file:

```css

@use postcss-import;
@use postcss-nested;
@use postcss-bem;
@use cssnext;
@use cssnano;

@import "_reset.css";

@import "components/_header.css";
@import "components/_box.css";


:root {
  --backgroundColor: #f0f0f0;
}
@custom-media --small-viewport (max-width: 320px);
@custom-media --smallish-viewport (max-width: 480px);

body {
  font-size: 16px;
  background-color: var(--backgroundColor);
}

.main-content {
  margin-bottom: 500px;
  &:before {
    @media (--small-viewport) {
      content: 'smallish';
    }
  }
}

```

I'm using gulp for now.  The task looks like:

```javascript

gulp.task('css', function () {
    var postcss = require('gulp-postcss');
    var use = require('postcss-use');
    return gulp.src(dev_path.css)
        .pipe(postcss([ use({ modules: ['postcss-import',
                                        'postcss-nested',
                                        'postcss-bem',
                                        'cssnext',
                                        'cssnano']}) ]))
        .pipe(gulp.dest(build_path.css));
});

```

Now if I have understood this plugin I could declare the use plugins in the css as above but instead use a wild card with the postcss task so 

```javascript

use({ modules: ['postcss-import',
                                        'postcss-nested',
                                        'postcss-bem',
                                        'cssnext',
                                        'cssnano']})

```

becomes:

```javascript

use({ modules: ['*']})

```

Sadly though this results in outputting an error:

```
ReferenceError: postcss-import is not a valid postcss plugin.
```
